### ISSUE TITLE
Get approval for MIT license addition from all contributors

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/aad-sso-wordpress#8]
Based on [VVV's license change](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/346), it appears it's important to get all contributor's ok to change a license. We're not changing, but adding a license, but please put your approval on this issue if you're for the MIT license being applied.

@blobaugh 
@psignoret
@ntonyho
@mmcachran

**Comment by psignoret** [comment]
Great idea. I  approve.

Will spin up the equivalent issue on mine.

**Comment by jtsternberg** [comment]
I think it's safe to say @ntonyho and @blobaugh approval on https://github.com/psignoret/aad-sso-wordpress/issues/27 will be effective here as well since their contributions precede this fork. Still waiting on @mmcachran

**Comment by mmcachran** [comment]
approved
